apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: fw877d22w-python 
  janus-idp.io/tekton: fw877d22w-python
  backstage.io/kubernetes-id: fw877d22w-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: fw877d22w-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml